// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Discord.NET.SupportExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DiscordSupportPackageString = "b4157286-7896-4e49-bb59-6016213b4f08";
        public static Guid DiscordSupportPackage = new Guid(DiscordSupportPackageString);

        public const string GroupSetString = "119bf355-ef7f-4cdf-af9a-8fe6b13c8658";
        public static Guid GroupSet = new Guid(GroupSetString);

        public const string CommandSetString = "c97d316c-21f9-4def-9731-4d63790b08fd";
        public static Guid CommandSet = new Guid(CommandSetString);

        public const string discordImagesString = "b4157286-21f9-4e49-9731-6016213b4f08";
        public static Guid discordImages = new Guid(discordImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CSharpProjectMenuGroup = 0x0100;
        public const int GenerateServerImageConfigurationCommand = 0x0010;
        public const int GenerateServerImageCommand = 0x0020;
        public const int bmpPic1 = 0x0001;
    }
}